fieldnames:
 - Action: 'Action'
 - By: 'By'
 - CommandLine: 'CommandLine'
 - From: 'From'
 - GID: 'GID'
 - Group: 'Group'
 - Home: 'Home'
 - List: 'List'
 - Origin: 'Origin'
 - Owner: 'Owner'
 - PWD: 'PWD'
 - Session: 'Session'
 - Shell: 'Shell'
 - TTY: 'TTY'
 - Type: 'Type'
 - UID: 'UID'
 - User: 'User'
 - Username: 'Username'
 - appname: 'appname'
 - hostname: 'hostname'
 - message: 'message'
 - pid: 'pid'
 - priority: 'priority'
 - timestamp: 'timestamp'
 